TICKET_TYPES = ("incident", "request", "problem")
TICKET_STATUSES = ("new", "assigned", "in_progress", "pending", "resolved", "closed")
TICKET_PRIORITIES = ("low", "medium", "high", "critical")
TICKET_OPEN_STATUSES = ("new", "assigned", "in_progress", "pending")
TICKET_CLOSED_STATUSES = ("resolved", "closed")